# Site settings
title: Ersan Doru
email: ersandoru@gmail.com
phone: "+90 530 435 53 66"
job_title: "Turkey Region Technical Manager at Kentkart"
location: "Izmir, Turkey"
description: > # this means to ignore newlines until "baseurl:"
  IT professional specializing in Public Transportation systems.
  Passionate about science, technology, anime, and learning new languages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ersandoru.github.io" # the base hostname & protocol for your site
twitter_username: ersandoru
github_username:  ersandoru
linkedin_username: ersandoru
steam_username: ersandoru

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
